# Generated by Django 4.0.4 on 2022-05-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionuser',
            name='type',
            field=models.CharField(choices=[('d', 'directory'), ('f', 'file')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
