# Generated by Django 4.0.4 on 2022-05-05 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 0, 7, 26, 429031)),
        ),
    ]
