# Generated by Django 4.0.4 on 2022-05-06 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 17, 51, 38, 986886)),
        ),
    ]
